archivist_task:
  description: >
    Conduct a research listing files and documents available from the inputs folder.
  expected_output: >
    A list of files and documents.
  agent: archivist

research_task:
  description: >
    Review the context you got and review the document for details of client fund subscriptions
  expected_output: >
    A list of clients and their fund subscriptions.
  agent: researcher

reporting_task:
  description: >
    Review the context you got and write a consolidated report of fund subscription positions.
  expected_output: >
    A fully fledged report showing subscription amounts by fund and client
    Formatted as markdown without '```'
  agent: reporting_analyst
